name: stub CI

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
    - name: Lint
      run: |
        npm i -g eslint eslint-plugin-json eslint-plugin-jsdoc
        npm run lint
    - name: Test
      run: |
        npm ci
        npm test
      env:
        CI: true
